// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtsdwsemddcxbvywddol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0c2R3c2VtZGRjeGJ2eXdkZG9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1OTA4MzQsImV4cCI6MjA2ODE2NjgzNH0.LTeIH383AC6vtK2W8QkP5DDsicz6RD2FLJNaVO4ah08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});